### ISSUE TITLE
Some options which hide footer for each AccordionItem?

### ISSUE THREAD

**Issue by alexTitakoff** [Lunrtick/vue-bulma-accordion#1]
Hello!

So nice component!

Tell me, please. Can I hide a footer-block? Native and using standard abilities of the component? 
Some option, like? 

thanks   :]

**Comment by Lunrtick** [comment]
Thanks Alex!

To hide a footer block, you have two options, as far as I know.

1. Don't provide a footer block ;). Useful if you were never using it.
2. Toggle the component you pass in to the footer using v-if or v-show. Like this...
```html
<BulmaAccordion>
    <BulmaAccordionItem>
        <button
        v-if="myToggleProperty"
        class="button is-primary"
        slot="footer">
            Click Me!
        </button>
    </BulmaAccordionItem>
</BulmaAccordion>
```
There aren't any built in methods of hiding the footer right now though

**Comment by alexTitakoff** [comment]
ok, thanks!
