### ISSUE TITLE
Javascript that can open and close an accordion

### ISSUE THREAD

**Issue by epochslee** [Lunrtick/vue-bulma-accordion#11]
I'm trying to figure out how I can open and close an accordion using javascript. What's the code for this or does it even exist?

**Comment by Lunrtick** [comment]
Currently there isn't a way to control the open items using JS (except for the initial state).

I think it would not be too difficult to add, as I imagine the accordion component would accept an array/object with booleans indicating the open/closed state, and would communicate changes back up to the parent, while also reading changes from the parent.

I don't have time to add this feature at the moment, though I do think it may be useful. You are most welcome to add it and submit a PR.
