### ISSUE TITLE
Accordion not showing expanded when using v-show

### ISSUE THREAD

**Issue by epochslee** [Lunrtick/vue-bulma-accordion#12]
Let's say I had something in the lines of this where only when showMembership is true, then the section with accordion will show. Well what happens is the accordion will show but always in a closed state. How I can force it to always show open?

```
<section class="accordions box notification is-info" v-show="showMembership">
  <bulma-accordion dropdown icon="plus-minus" :initial-open-items="[1]"> 
    <bulma-accordion-item>
      SOME CONTENT
    </bulma-accordion-item>
  </bulma-accordion>
</section>

<script>
export default {
  data: function() {
    return {
      showMembership: false
    };
    mounted() {
      this.$events.$on("someEvent", element => {
        this.showMembership = true;
      });
    }
  }
</script>
```

**Comment by Lunrtick** [comment]
You can change `v-show` to `v-if` - I think that will fix the problem.

Because of the way accordion items determine their height, when they are hidden with `v-show` they probably see their height as 0. Forcing a fresh render when the property is changed should get you the behaviour you want.
