### ISSUE TITLE
How to make first accordion open by default

### ISSUE THREAD

**Issue by Mobeidat** [Lunrtick/vue-bulma-accordion#3]

**Comment by Lunrtick** [comment]
Hey Mobeidat

I'm actually working on updating and upgrading this component at the moment.

I am adding this feature, and will publish the changes soon - the API will likely allow something like
```vue
<BulmaAccordion :initialOpenItem="[true, false, false]"></BulmaAccordion>
```
which will let you specify which items should be open initially. If the `dropdown` option is false, only the last true value will apply.

I'll leave this issue open until my changes are live.

**Comment by Lunrtick** [comment]
Okay - the new version is ready to use now.

There are two options that solve your problem, and they're nicely documented in the README now, so take a look there!
