### ISSUE TITLE
:initialopenitem not working after the update

### ISSUE THREAD

**Issue by Mobeidat** [Lunrtick/vue-bulma-accordion#4]
Hello,

Can you put an example on how to use :initialopenitem or :initialopenitems?

It's not working 

Thanks,

**Comment by Lunrtick** [comment]
I'm working on adding some more examples.

Not sure if this applies to you, but you may want to look at the Vue docs on props [here](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case).

Here's an example
```vue
<BulmaAccordion initial-open-item="1">
  <BulmaAccordionItem>
    <p slot="title">Title</p>
  </BulmaAccordionItem>
  <BulmaAccordionItem>
    <p slot="title">Title</p>
  </BulmaAccordionItem>
</BulmaAccordion>
```

**Comment by Mobeidat** [comment]
Still not working 

Here's my code

            <BulmaAccordion
            :dropdown="false"
            :icon="'custom'"
            class="w-100"
            initial-open-item="'1'"
            :caretAnimation="{
                  duration: '.6s',
                  timerFunc: 'ease-in-out'
              }"
              :slide="{
                  duration: '.9s',
                  timerFunc: 'none'
              }"

**Comment by Lunrtick** [comment]
`initial-open-item="'1'"` means you're passing the string " **'**1**'** ", instead of the string "1".

Either do `:initial-open-item="'1'"` or simply `initial-open-item="1"`
