### ISSUE TITLE
Import not working after 0.4.*

### ISSUE THREAD

**Issue by dermansi** [Lunrtick/vue-bulma-accordion#7]
I can't use the component after the update to 0.4.*

It says:

> Failed to compile. ./node_modules/vue-bulma-accordion/dist/vue-bulma-accordion.common.js
> Module build failed: Error: ENOENT: no such file or directory, open '/src/node_modules/vue-bulma-accordion/dist/vue-bulma-accordion.common.js'

I use the following in my component:
`
import { BulmaAccordion, BulmaAccordionItem } from 'vue-bulma-accordion';`

Am I doing something wrong?

**Comment by Lunrtick** [comment]
It seems like your build tool is looking in the wrong

**Comment by dermansi** [comment]
I'm using webpack. It's the vue webpack starter template

**Comment by Lunrtick** [comment]
Can you share your webpack config?

Also, is there any particular reason you're using the starter template instead of the new Vue CLI?

**Comment by dermansi** [comment]
I'm on mobile, I can share tomorrow. But it's the base config. The project is older than vue cli 3 that's why we still use the starter.
