### ISSUE TITLE
Unable to give background color

### ISSUE THREAD

**Issue by mapkbalaji** [Lunrtick/vue-bulma-accordion#8]
I am unable to set different background color to header, content and footer. Is this option not available or is there some way to achieve this?

**Comment by Lunrtick** [comment]
Here's a quick pen - you have to work with the classes that you'll see in `BulmaAccordionItem.vue`.
https://codepen.io/lunrtick/pen/LaZWjJ

**Comment by mapkbalaji** [comment]
How did you use the class `.card-header` from `BulmaAccordionItem.vue` into your code? I've been trying but in vain. I have a component named Projects.vue in which, I'm using the accordion. When defining the class in the style tag, nothing happens. 

The main reason I needed this is, to resize the title icon. The icon appears huge as in the attached screenshot. This is the only view in which I could see two accordions to grab a screenshot.
![accordionhugeicon](https://user-images.githubusercontent.com/20077402/54043361-6c841f80-41f2-11e9-9321-d40f30af675c.jpg)

**Comment by Lunrtick** [comment]
You've obviously got some custom CSS there - it's quite hard to figure out what the problem is without having something in front of me.

Can you reproduce this in a jsfiddle or codepen or similar?

**Comment by mapkbalaji** [comment]
Thanks. I had my parent component "scoped" and hence, the styles wouldn't apply to the bulma-accordion component. I removed the scope and everything is working fine.
